-- 코드를 입력하세요
SELECT USU.USER_ID, USU.NICKNAME, SUM(USB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS USB
JOIN USED_GOODS_USER AS USU
on USB.WRITER_ID = USU.USER_ID
WHERE STATUS = "DONE"
GROUP BY  USB.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES