-- 코드를 입력하세요
SELECT ROUND(SUM(DAILY_FEE) / COUNT(*), 0) AS AVERAGE_FEE
# SELECT SUM(DAILY_FEE), COUNT(*), SUM(DAILY_FEE) / COUNT(*), ROUND(SUM(DAILY_FEE) / COUNT(*),0)
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = "SUV"
GROUP BY CAR_TYPE
