-- 코드를 입력하세요
SELECT DISTINCT(CC.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS CC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRH
ON CC.CAR_ID = CRH.CAR_ID
WHERE YEAR(CRH.START_DATE)=2022 AND MONTH(CRH.START_DATE) =10 AND CAR_TYPE LIKE '%세단%'
ORDER BY 1 DESC