name: Update Recent Solutions
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"   # 매일 00:00 UTC (KST 09:00)
jobs:
  update:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.x" }
      - name: Update README recent list
        run: |
          python3 scripts/update_recent.py
      - name: Commit & Push if changed
        run: |
          if git diff --quiet README.md; then
            echo "No changes."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore(readme): update recent solutions"
            git push
          fi
